#!/bin/zsh
eval "$(fnm env --use-on-cd --shell zsh)"

# ~/ Clean-up
export XDG_CONFIG_HOME="$HOME/.config"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export TOOLS="$HOME/.tools"
export LOCAL_BIN="$HOME/.local"
export PATH="$LOCAL_BIN/bin:$PATH"

case "$(uname -s)" in
	Darwin)
		eval "$(/opt/homebrew/bin/brew shellenv zsh)"
		export PATH="$PATH:${HOME}/Library/npm"
		;;
	Linux)
		export GOPATH="$HOME/.local/src/go"
		export PATH="$PATH:${$(find -L ~/.local/bin -type d -printf %p:)%%:}:$GOPATH/bin"

		# Default programs:
		export EDITOR="nvim"
		export TERMINAL="st"
		export BROWSER="firefox"

		export XDG_DATA_HOME="$HOME/.local/share"
		export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
		export STARTX="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

		[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1
		;;
esac
